### ISSUE TITLE
Weights/avoid overlap?

### ISSUE THREAD

**Issue by ckald** [tpoisot/nxfa2#2]
Hi. I'm looking at your implementation of the algorithm and don't seem to find the nodes sizes and avoid overlap features. Did you omit them?

**Comment by tpoisot** [comment]
Yes.

Sent from a mobile device - pardon the brevity/typos.

-------- Message d'origine --------
De : Andrii Magalich notifications@github.com 
Date : 06/15/2015  8:35 AM  (GMT-05:00) 
À : tpoisot/nxfa2 nxfa2@noreply.github.com 
Objet : [nxfa2] Weights/avoid overlap? (#2) 

Hi. I'm looking at your implementation of the algorithm and don't seem to find the nodes sizes and avoid overlap features. Did you omit them?

**Comment by ckald** [comment]
Thanks :)
